// Generated by gencpp from file local_map/SaveMap.msg
// DO NOT EDIT!


#ifndef LOCAL_MAP_MESSAGE_SAVEMAP_H
#define LOCAL_MAP_MESSAGE_SAVEMAP_H

#include <ros/service_traits.h>


#include <local_map/SaveMapRequest.h>
#include <local_map/SaveMapResponse.h>


namespace local_map
{

struct SaveMap
{

typedef SaveMapRequest Request;
typedef SaveMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveMap
} // namespace local_map


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::local_map::SaveMap > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::local_map::SaveMap&) { return value(); }
};

template<>
struct DataType< ::local_map::SaveMap > {
  static const char* value()
  {
    return "local_map/SaveMap";
  }

  static const char* value(const ::local_map::SaveMap&) { return value(); }
};


// service_traits::MD5Sum< ::local_map::SaveMapRequest> should match 
// service_traits::MD5Sum< ::local_map::SaveMap > 
template<>
struct MD5Sum< ::local_map::SaveMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::local_map::SaveMap >::value();
  }
  static const char* value(const ::local_map::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::local_map::SaveMapRequest> should match 
// service_traits::DataType< ::local_map::SaveMap > 
template<>
struct DataType< ::local_map::SaveMapRequest>
{
  static const char* value()
  {
    return DataType< ::local_map::SaveMap >::value();
  }
  static const char* value(const ::local_map::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::local_map::SaveMapResponse> should match 
// service_traits::MD5Sum< ::local_map::SaveMap > 
template<>
struct MD5Sum< ::local_map::SaveMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::local_map::SaveMap >::value();
  }
  static const char* value(const ::local_map::SaveMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::local_map::SaveMapResponse> should match 
// service_traits::DataType< ::local_map::SaveMap > 
template<>
struct DataType< ::local_map::SaveMapResponse>
{
  static const char* value()
  {
    return DataType< ::local_map::SaveMap >::value();
  }
  static const char* value(const ::local_map::SaveMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCAL_MAP_MESSAGE_SAVEMAP_H
